#!/bin/bash

set -e -x

# Needed by Bundler 1.3: https://github.com/carlhuda/bundler/issues/2382
export RUBYOPT='-rrbconfig'

echo "Bundling Standalone so we can run the specs w/o bundler loaded"

bundle install --standalone --binstubs

echo "Running all..."

bin/rspec spec -b --format progress --profile

echo
echo "--------------------------------------------------------------------"
echo

if [[ $TRAVIS_RUBY_VERSION =~ ^jruby ]]; then
	export JRUBY_OPTS='-X-C' # disable JIT since these processes are so short lived
	bin/rspec -b --format progress `find spec -iname '*_spec.rb'`
else
	for file in `find spec -iname '*_spec.rb'`; do
	  bin/rspec $file -b --format progress
	done
fi

# Prepare RUBYOPT for scenarios that are shelling out to ruby,
# and PATH for those that are using `rspec` or `rake`.
# RUBYOPT="-I${PWD}/bundle -rbundler/setup" \
#   PATH="${PWD}/bin:$PATH" \
#   bin/cucumber

# For now, use this instead, due to a bug in bundler:
# https://github.com/carlhuda/bundler/issues/2382
bundle exec bin/cucumber

